export type ICreateProperty = {
  type: string;
  size: number;
  price: number;
  media_id: number;
  media_commision: number;
  "address.line1": string;
  "address.line2": string;
  "address.plot": string;
  "address.road": string;
  "address.sector": string;
  "address.block": string;
  "address.area": string;
  "address.city": string;
  "address.country": string;
  "flat.floor": number;
  "flat.apt_no": string;
  "flat.house_no": string;
  "flat.num_bathroom": number;
  "flat.num_bedroom": number;
  "flat.num_balcony": number;
  "flat.has_parking": boolean;
  "flat.has_lift": boolean;
  "flat.facing_side": string;
  "flat.is_used": boolean;
  "flat.handovered_at": string;
};
export type IUpdateProperty = {
  first_name: string;
  last_name: string;
  gender: string;
  password: string;
  display_picture: string;
  email: string;
  phone: string;
  dob: string;
  hired_date: string;
  work_hour: number;
  salary: number;
  bank: string;
  address: string;
};
